# Generated by Django 4.1.5 on 2023-03-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class0', models.CharField(max_length=16)),
                ('class1', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('barcode', models.CharField(max_length=13)),
                ('num', models.IntegerField()),
                ('input_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trade_mark', models.CharField(max_length=64)),
                ('spec', models.CharField(max_length=64)),
                ('is_on_sale', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_filed', models.BooleanField(default=False)),
                ('class1_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.goodsclass')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.warehouse')),
            ],
        ),
    ]
