# Generated by Django 4.1.5 on 2023-03-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='class1_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='input_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_filed',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='num',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='trade_mark',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse_id',
        ),
    ]
