# Generated by Django 4.1.5 on 2023-03-17 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_stock_class1_id_remove_stock_input_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='class1_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sms.goodsclass'),
        ),
        migrations.AddField(
            model_name='stock',
            name='input_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='spec',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='trade_mark',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sms.warehouse'),
        ),
    ]
